import { Html, Head, Main, NextScript } from 'next/document'
import Footer from '../components/Footer'

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
    
  )
}

// The _document.js file in a Next.js application is used 
// to define the HTML structure and other properties of the
// document that is sent to the browser.

// In a Next.js application, the _document.js file acts as
// a custom document that is used in place of the default 
// document generated by Next.js. The purpose of the _document.js
// file is to allow you to have fine-grained control over the
// HTML that is sent to the browser, which is not possible with
// the default document.

// In the _document.js file, you can specify the HTML structure of
// the document, include styles and scripts, set the <head> of the
// document, and more. This allows you to have full control over
// the HTML that is sent to the browser, which is necessary for 
// things like SEO optimization and accessibility.

// So in a nutshell, the _document.js file is used to define the HTML``
// structure and other properties of the document that is sent to the
// browser, and it provides a way for you to have fine-grained control
// over the HTML that is sent to the browser.